services:
  backend:
    image: awive-configurator:${ENV:-dev}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "8000:8000"
