version: "3.9"

services:
  backend:
    image: awive-configurator-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - ENV=production
